apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
  namespace: demo
data:
  definitions.json: |-
    # RabbitMQ definitions go here
  enabled_plugins: '[rabbitmq_peer_discovery_k8s, rabbitmq_prometheus, rabbitmq_management].'
  rabbitmq.conf: |
    loopback_users.guest = false
